### ISSUE TITLE
 storing destination message... ERROR

### ISSUE THREAD

**Issue by laouache** [wrzlbrmft/imapcopy#1] opened 2015-06-18 10:27 UTC
hello,

source reading ok and destination connexion ok.
but when transfering mail i have this error message 

*** recursively copying folders and messages...
    ... (f:1/239) 'ÃlÃ©ments envoyÃ©s'
        opening source folder... OK
        source folder message(s): 15060
        destination folder: 'ÃlÃ©ments envoyÃ©s'
        creating destination folder... ERROR
        opening destination folder... OK

       ... (f:1/239;m:33/15060,33/183189) 'RE: tres tres urgent'
            source message date is 13-Jul-2011 17:13:00 +0200
            loading source message (314808 byte(s))... 364274 byte(s) read
            storing destination message... ERROR

**Comment by wrzlbrmft** [comment] 2015-06-19 08:21
In order to help you I need more information:
- Involved IMAP servers
- Where is imapcopy running? OS? PHP version?
- What type of migration are you trying to do? E.g. is it an empty destination mailbox or are there pre-existing folders?

imapcopy fails in creating destination folder 1 ("ÃlÃ©ments envoyÃ©s"). The name looks awkward, so what is the actual name of this folder in the source mailbox? Does it already exist in the destination mailbox? With the correct name?

Also, your output looks incomplete: Your second error is about message 33 in folder 1. What happened to the 32 message before? Were they copied successfully?

**Comment by laouache** [comment] 2015-06-19 09:16
Hi, thanks for your time,

Involved IMAP servers ==> Office 365 src et Gmail (or Yahoo, i tried both) dest
Where is imapcopy running? OS? PHP version? ==> on hosted server on ubuntu 14.04 LTS and php 5.5.9-1ubuntu4.9 (all up to date)
What type of migration are you trying to do? E.g. is it an empty destination mailbox or are there pre-existing folders?  ==> complete migration but i tried for one directory to test and find error. it is an empty mailbox but i tried also to create a directory to test with a name not in the source list. 

ÃlÃ©ments envoyÃ©s is in fact "éléments envoyés" in french "sent items" and it exist not in mail destination mailbox.

yes it was a example, all of them have the same error.

![image](https://cloud.githubusercontent.com/assets/12950619/8250438/19fd9064-1674-11e5-964d-5684a38c2e7a.png)

and here is my config.json

{
    "src": {
        "hostname": "outlook.office365.com",
        "port": 993,
        "username": "axxxm",
        "password": "1xxx0",
        "ssl": true,
        "sslNovalidateCert": true,
        "readOnly": true,
        "folderSeparator": ".",

        "excludedFolders": [
            "INBOX.Drafts",
            "INBOX.Spam",
            "INBOX.Trash"
        ],
        "onlyFoldersNum": [1, 2, 3],
        "onlyFolderMessagesNum": {},
        "startFolderNum": 1,
        "startFolderMessageNum": 1
    },
    "dst": {
        "hostname": "imap.gmail.com",
        "port": 993,
        "username": "nxfr",
        "password": "xx1",
        "ssl": true,
        "sslNovalidateCert": true,
        "readOnly": false,
        "folderSeparator": "/",

        "trimFolderPath": true,
        "mappedFolders": {
            "INBOX/Sent": "[Gmail]/Gesendet"
        },
        "popFolder": "",
        "pushFolder": ""
    }
}

**Comment by laouache** [comment] 2015-06-19 11:47
I confirm it works on directory with non specials characters. 
![image](https://cloud.githubusercontent.com/assets/12950619/8252829/c4c17fc8-1689-11e5-888d-f2da0caf812d.png)

**Comment by wrzlbrmft** [comment] 2015-06-19 12:56
Character encoding was also my first assumption because of the strange folder name, but I wanted to be sure. So the problem is, that the folder cannot be created in the destination mailbox because of some wrong character encoding and therefore the messages of the folder cannot be copied either.

I am not sure if it helps, but before PHP 5.6.0 the "default_charset" setting in php.ini is not set specifically. I always change it to "UTF-8":

```
default_charset = "UTF-8"
```

Maybe you can give it a try? For command-line PHP, Ubuntu uses /etc/php5/cli/php.ini and the setting is somewhere near line 690-700.

If that doesn't help, I also have access to an Office 365 mailbox for testing (probably over the weekend).

**Comment by laouache** [comment] 2015-06-19 13:38
I checked with this config of charset, I verified it with phpinfo too. 
But the error remain the same.

I'm waiting for your test.

Thanks

**Comment by laouache** [comment] 2015-06-23 11:45
Hello,

Were you able to make the tests ?

**Comment by wrzlbrmft** [comment] 2015-06-23 12:59
I just did the test and unfortunately - or luckily ;-) - it worked for me: I created a folder "éléments envoyés" in my Office 365 account, stored one test message in it and successfully copied it to another Gmail account (using `onlyFoldersNum` containing just this folder):

```
*** opening source
    connecting via '{outlook.office365.com:993/imap/ssl/readonly}'... OK
>>> source is ready

*** opening destination
    connecting via '{imap.gmail.com:993/imap/ssl}'... OK
>>> destination is ready

*** Counting total source folders... OK
>>> 49 total source folder(s) found

*** counting total source messages...

[...]

    ... (f:7/49) 'INBOX/éléments envoyés'
        opening source folder... OK
        counting source folder messages... 1 source folder message(s) found

[...]

>>> 17558 total source message(s) found

*** recursively copying folders and messages...
    ... (f:7/49) 'INBOX/éléments envoyés'
        opening source folder... OK
        source folder message(s): 1
        destination folder: 'éléments envoyés'
        creating destination folder... OK
        opening destination folder... OK

        ... (f:7/49;m:1/1,3775/17558) 'Test'
            source message date is 19-May-2015 09:48:50 +0200
            loading source message (20988 byte(s))... 11586 byte(s) read
            storing destination message... OK
```

![screenshot](https://cloud.githubusercontent.com/assets/10922028/8306442/4dc28aa2-19b8-11e5-9768-ecd411d9d9c4.png)

Interestingly my console output also writes the correct folder name: "éléments envoyés" and not "ÃlÃ©ments envoyÃ©s". I guess the problem is not my script but your configuration.
As said, I configured PHP to use UTF-8 and also my system is using a UTF-8 locale:

```
matthias@localhost.localdomain:~$ locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

The only workaround I can think of for now (and of course without needing your e-mail credentials) is to put the affected folder names (in their wrong spelling I guess) into the `mappedFolders` configuration setting to be mapped to something ascii-only.

You can test it by calling imapcopy with the `-test` option. When copying one of the affected folders the "destination folder:" console output should show the folder name you mapped it to bit SKIP it's creation.

**Comment by wrzlbrmft** [comment] 2015-07-23 08:54
Closing issue.

**Closed by wrzlbrmft** 2015-07-23 08:54 UTC
